"""One-shot OAuth2 confidential-client registration against a deployed OpenEMR.

POSTs to ``/oauth2/default/registration`` with a ``jwks: {"keys": [<JWK>]}``
payload (RFC 7591 + SMART Backend Services), so OpenEMR's confidential-client
OAuth2 endpoint accepts ``system/*`` scopes; static-secret registration is
hard-rejected at ``src/RestControllers/AuthorizationController.php`` lines
312-317. The matching private key (generated by
``scripts/generate_client_keypair.py``) goes into ``OAUTH_PRIVATE_KEY_PEM``;
the registration response's ``client_id`` becomes ``OAUTH_CLIENT_ID``.

Run it once per deployed OpenEMR. Re-running creates a separate registration
that competes for the same ``kid``; revoke the old client via the API
Clients admin page if you need to clean up.

Requires (in OpenEMR globals → Connectors, all checked + saved):

- Enable OpenEMR Standard FHIR REST API
- Enable OpenEMR FHIR System Scopes ← without this, OpenEMR strips ``system/*``
  scopes silently
- Enable OpenEMR Standard REST API

Usage::

    uv run python scripts/register_oauth_client.py \\
        --openemr-url https://openemr.example.com \\
        --jwk public-jwk.json
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import httpx

DEFAULT_SCOPES = (
    "system/Patient.read",
    "system/Condition.read",
    "system/MedicationRequest.read",
    "system/AllergyIntolerance.read",
    "system/Observation.read",
    "system/Encounter.read",
    "system/DocumentReference.read",
)


def build_payload(jwk: dict[str, object], openemr_url: str) -> dict[str, object]:
    """Assemble the registration body OpenEMR's RFC 7591 endpoint accepts.

    ``token_endpoint_auth_method`` is ``private_key_jwt`` because that's the
    SMART Backend Services flow ``CustomClientCredentialsGrant`` validates;
    using the older ``client_secret_post`` would cause OpenEMR to reject
    every ``system/*`` scope at registration.
    """
    return {
        "application_type": "private",
        "client_name": "Clinical Co-Pilot Agent Service",
        "redirect_uris": [openemr_url.rstrip("/") + "/"],
        "token_endpoint_auth_method": "private_key_jwt",
        "grant_types": ["client_credentials"],
        "jwks": {"keys": [jwk]},
        "scope": " ".join(DEFAULT_SCOPES),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--openemr-url",
        required=True,
        help="Base URL of the deployed OpenEMR (e.g. https://openemr.example.com).",
    )
    parser.add_argument(
        "--jwk",
        type=Path,
        required=True,
        help="Path to the JWK JSON file produced by generate_client_keypair.py.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("oauth-registration.json"),
        help="Where to save the full registration response (default: ./oauth-registration.json).",
    )
    parser.add_argument(
        "--timeout",
        type=float,
        default=30.0,
        help="HTTP timeout in seconds (default 30).",
    )
    args = parser.parse_args(argv)

    jwk = json.loads(args.jwk.read_text())
    if not isinstance(jwk, dict) or jwk.get("kty") != "RSA":
        print(f"--jwk file does not contain an RSA JWK: {args.jwk}", file=sys.stderr)
        return 2

    payload = build_payload(jwk, args.openemr_url)
    url = args.openemr_url.rstrip("/") + "/oauth2/default/registration"

    print(f"POSTing OAuth2 client registration to {url} ...", file=sys.stderr)
    response = httpx.post(
        url,
        json=payload,
        headers={"Accept": "application/json"},
        timeout=args.timeout,
    )

    body_text = response.text
    args.out.write_text(body_text)

    if response.status_code >= 400:
        print(
            f"\nRegistration failed: status={response.status_code}\n{body_text}",
            file=sys.stderr,
        )
        return 1

    body = response.json()
    client_id = body.get("client_id", "<missing>")
    print(f"\nRegistration succeeded. client_id={client_id}", file=sys.stderr)
    print(f"Full response saved to {args.out}.", file=sys.stderr)
    print("Set OAUTH_CLIENT_ID on the deployed agent-service.", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
